name: Main Workflow
on:
 push:
  branches: ['main']
 workflow_dispatch: 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: kitabisa/sonarcloud-github-action@v1.1.1
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }} # Usa la variable de entorno
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}       # Usa la variable de entorno

