name: Main Workflow
on:
 push:
  branches: ['main']
 workflow_dispatch: 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn -B clean install
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }} # Usa la variable de entorno
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}       # Usa la variable de entorno
     # - name: Debugging
     #   run: |
     #       echo "Starting the workflow..."
     #       echo "The current working directory is:"
     #       pwd
     #       echo "Listing files and directories in the current directory..."
     #       ls -la
            
     #       echo "----------------------------------------"
     #       echo "Changing to the 'target' directory..."
     #       cd target
     #       echo "The new working directory is:"
     #       pwd
     #       echo "Listing files and directories in 'target'..."
     #       ls -la
     
                

