name: Main Workflow
on:
 push:
  branches: ['main']
 workflow_dispatch: 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        with:
          host: '${{ secrets.SONARQUBE_HOST }}'
          login: '${{ secrets.SONARQUBE_TOKEN }}'
