name: Main Workflow
on:
 push:
  branches: ['main']
 workflow_dispatch: 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }} # Usa la variable de entorno
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}       # Usa la variable de entorno
      - name: Debugging
        run: |
          echo "Starting the SonarQube analysis..."
          echo "The current working directory is:"
          pwd
        

